packages:
  - src/web
  - mcps/*
  - docs

allowBuilds:
  '@biomejs/biome': true
  '@discordjs/opus': set this to true or false
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - "@discordjs/opus"
